# NumPy Practice Notebook — Day 6

## Objective
Demonstrate NumPy and its use for numerical data analysis.

### Topics
- 1D, 2D, and 3D arrays
- Dimensions, shape, size, and data types
- Indexing and slicing
- Reshaping
- `zeros()`, `ones()`, `arange()`, `linspace()`
- Mathematical and vectorized operations
- Boolean masking
- Broadcasting
- Aggregate functions


In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy imported successfully.


## 1. Creating a 1D Array

In [2]:
arr_1d = np.array([10, 20, 30, 40, 50])
print(arr_1d)
print("Dimensions:", arr_1d.ndim)
print("Shape:", arr_1d.shape)
print("Size:", arr_1d.size)
print("Data type:", arr_1d.dtype)

[10 20 30 40 50]
Dimensions: 1
Shape: (5,)
Size: 5
Data type: int64


## 2. Creating a 2D Array

In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d)
print("Dimensions:", arr_2d.ndim)
print("Shape:", arr_2d.shape)
print("Data type:", arr_2d.dtype)

2D Array:
[[1 2 3]
 [4 5 6]]
Dimensions: 2
Shape: (2, 3)
Data type: int64


## 3. Creating a 3D Array

In [4]:
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr_3d)
print("Dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)
print("Data type:", arr_3d.dtype)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)
Data type: int64


## 4. Indexing and Slicing

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print("First:", arr[0])
print("Third:", arr[2])
print("Last:", arr[-1])
print("First three:", arr[:3])
print("Index 2 to 4:", arr[2:5])
print("Every second:", arr[::2])

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n2D element [1,2]:", matrix[1,2])
print("First two rows:")
print(matrix[:2])
print("First two columns:")
print(matrix[:, :2])

First: 10
Third: 30
Last: 50
First three: [10 20 30]
Index 2 to 4: [30 40 50]
Every second: [10 30 50]

2D element [1,2]: 6
First two rows:
[[1 2 3]
 [4 5 6]]
First two columns:
[[1 2]
 [4 5]
 [7 8]]


## 5. Reshaping Arrays

In [6]:
original = np.arange(1, 13)
reshaped = original.reshape(3, 4)

print("Original:")
print(original)
print("\nReshaped (3 x 4):")
print(reshaped)
print("\nShape:", reshaped.shape)

Original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped (3 x 4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)


## 6. Array Generation Functions

In [7]:
print("zeros():")
print(np.zeros((2,3)))

print("\nones():")
print(np.ones((2,3)))

print("\narange():")
print(np.arange(0, 20, 2))

print("\nlinspace():")
print(np.linspace(0, 1, 6))

zeros():
[[0. 0. 0.]
 [0. 0. 0.]]

ones():
[[1. 1. 1.]
 [1. 1. 1.]]

arange():
[ 0  2  4  6  8 10 12 14 16 18]

linspace():
[0.  0.2 0.4 0.6 0.8 1. ]


## 7. Mathematical Operations

In [8]:
numbers = np.array([1, 2, 3, 4, 5])

print("Original:", numbers)
print("Square:", numbers ** 2)
print("Add 10:", numbers + 10)
print("Multiply by 3:", numbers * 3)
print("Divide by 2:", numbers / 2)
print("Square root:", np.sqrt(numbers))

Original: [1 2 3 4 5]
Square: [ 1  4  9 16 25]
Add 10: [11 12 13 14 15]
Multiply by 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


## 8. Vectorized Operations

In [9]:
marks = np.array([65, 72, 81, 90, 55])

print("Marks:", marks)
print("After +5 bonus:", marks + 5)
print("As proportions:", marks / 100)
print("Marks >= 70:", marks >= 70)

Marks: [65 72 81 90 55]
After +5 bonus: [70 77 86 95 60]
As proportions: [0.65 0.72 0.81 0.9  0.55]
Marks >= 70: [False  True  True  True False]


## 9. Boolean Masking

In [10]:
values = np.array([12, 25, 7, 40, 18, 33])

mask = values > 20
print("Mask:", mask)
print("Values > 20:", values[mask])
print("Values between 10 and 30:",
      values[(values >= 10) & (values <= 30)])

Mask: [False  True False  True False  True]
Values > 20: [25 40 33]
Values between 10 and 30: [12 25 18]


## 10. Broadcasting

In [11]:
matrix = np.array([[10,20,30],
                   [40,50,60]])
row_values = np.array([1,2,3])

print("Matrix:")
print(matrix)
print("\nRow values:", row_values)
print("\nAfter broadcasting:")
print(matrix + row_values)

Matrix:
[[10 20 30]
 [40 50 60]]

Row values: [1 2 3]

After broadcasting:
[[11 22 33]
 [41 52 63]]


## 11. Aggregate Functions

In [12]:
data = np.array([10,20,30,40,50])

print("Sum:", np.sum(data))
print("Mean:", np.mean(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))
print("Median:", np.median(data))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0


## 12. Aggregate Functions on 2D Arrays

In [13]:
scores = np.array([[10,20,30],
                       [40,50,60]])

print("Total:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Median:", np.median(scores))
print("Column-wise sum:", np.sum(scores, axis=0))
print("Row-wise sum:", np.sum(scores, axis=1))

Total: 210
Mean: 35.0
Minimum: 10
Maximum: 60
Median: 35.0
Column-wise sum: [50 70 90]
Row-wise sum: [ 60 150]


## 13. Combined Numerical Analysis Example
The following example combines vectorization, masking, and aggregate functions.

In [14]:
student_marks = np.array([78, 65, 92, 55, 88, 71, 96, 63])

passed = student_marks[student_marks >= 50]
bonus_marks = np.minimum(student_marks + 5, 100)

print("Original marks:", student_marks)
print("Passed marks:", passed)
print("After 5-mark bonus:", bonus_marks)
print("Average:", np.mean(student_marks))
print("Highest:", np.max(student_marks))
print("Lowest:", np.min(student_marks))
print("Median:", np.median(student_marks))
print("Total:", np.sum(student_marks))

Original marks: [78 65 92 55 88 71 96 63]
Passed marks: [78 65 92 55 88 71 96 63]
After 5-mark bonus: [ 83  70  97  60  93  76 100  68]
Average: 76.0
Highest: 96
Lowest: 55
Median: 74.5
Total: 608


## 14. Key Observations

1. NumPy arrays efficiently store and process numerical data.
2. `ndim`, `shape`, `size`, and `dtype` describe an array's structure.
3. Indexing and slicing provide flexible access to array elements.
4. `reshape()` changes the arrangement of elements while preserving the number of elements.
5. `zeros()`, `ones()`, `arange()`, and `linspace()` simplify array creation.
6. Vectorized operations perform element-wise calculations without explicit loops.
7. Boolean masking filters values using logical conditions.
8. Broadcasting allows compatible arrays with different shapes to work together.
9. Aggregate functions provide useful numerical summaries.

## Conclusion

NumPy provides an efficient foundation for numerical data analysis in Python. Its arrays, vectorized operations, masking, broadcasting, reshaping, and aggregate functions are widely used in data science and machine learning.
